version: "3"
services:
  strapi:
    container_name: strapi
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: mystrapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      STRAPI_ADMIN_API_TOKEN: ${STRAPI_ADMIN_API_TOKEN}                                                                                                                                                                                                                  
      STRAPI_ADMIN_LIVE_STRIPE_SECRET_KEY: ${STRAPI_ADMIN_LIVE_STRIPE_SECRET_KEY}                                                                                                                                                                                                  
      STRAPI_ADMIN_TEST_STRIPE_SECRET_KEY: ${STRAPI_ADMIN_TEST_STRIPE_SECRET_KEY}
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock # Replace with package-lock.json if using npm
      - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB
  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    env_file: .env
    image: arm64v8/mysql:8.3
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./.data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - "3306:3306"
    networks:
      - strapi
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: strapiDB
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
    strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge